---
- hosts: all
  sudo: yes
  tasks:
  - name: System upgrade
    apt: update_cache=yes upgrade=yes
  - name: Install packages
    apt: name={{ item }} state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - sqlite3
      - mysql-server
      - redis-server
      - python-pycurl
      - libpcre3-dev
  - name: Run mysql-server
    service: name=mysql state=running
  - name: Add dotdeb repository
    apt_repository: repo='deb http://packages.dotdeb.org wheezy-php56-zts all' state=present
  - name: Add dotdeb key
    apt_key: url='https://www.dotdeb.org/dotdeb.gpg' state=present
  - name: Add mongodb repository
    apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' state=present
  - name: Add mongodb key
    apt_key: url='https://docs.mongodb.org/10gen-gpg-key.asc' state=present validate_certs=no
  - name: Install from custom repository
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
    - mongodb-org
    - php5-cli
    - php5-fpm
    - php5-redis
    - php5-mysql
    - php5-sqlite
    - php5-dev
  - name: Install PECL threads.
    command: "pecl install pthreads"
    register: pecl_result
    changed_when: "pecl_result.rc == 0"
    failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  - name: Enable pthreads
    copy: content="extension=pthreads.so" dest=/etc/php5/{{ item }}/conf.d/10-pthreads.ini owner=root group=root
    with_items:
    - fpm
    - cli
    notify:
    - restart php5-fpm
  - name: Install composer
    get_url: url=https://getcomposer.org/composer.phar dest=/usr/bin/composer mode=0444
  handlers:
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted




